openapi: 3.0.0
info:
  title: Menu Aggregate Service
  description: |
    Provides a REST API for aggregated queries of dishes with reviews or ratings. 
    This service does not store data in the database but retrieves it from the Menu Service and Orders Service using non-blocking calls (Spring WebFlux).
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /v1/menu-aggregate/{menuId}:
    get:
      summary: Get information about a dish with reviews
      description: |
        Retrieves information about a dish, including a list of reviews. The list of reviews is paginated and sorted by creation date.
      parameters:
        - name: menuId
          in: path
          required: true
          description: ID of the dish
          schema:
            type: string
        - name: sort
          in: query
          required: false
          description: Sorting order of reviews by creation date (DATE_ASC, DATE_DESC)
          schema:
            type: string
            enum: [DATE_ASC, DATE_DESC]
        - name: from
          in: query
          required: false
          description: Starting point for pagination
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          description: Number of reviews per page
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Information about the dish with reviews
          content:
            application/json:
              schema:
                type: object
                properties:
                  menuId:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                    format: float
                  availability:
                    type: boolean
                  reviews:
                    type: array
                    items:
                      type: object
                      properties:
                        reviewId:
                          type: string
                        rating:
                          type: number
                          format: float
                        comment:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
        '400':
          description: Bad request (invalid parameters)
        '404':
          description: Dish not found

  /v1/menu-aggregate:
    get:
      summary: Get information about dishes from a specified category
      description: |
        Retrieves information about dishes from a specified category. Dishes can be sorted by name (AZ, ZA), price (PRICE_ASC, PRICE_DESC), creation date (DATE_ASC, DATE_DESC), or rating (RATE_ASC, RATE_DESC).
      parameters:
        - name: category
          in: query
          required: true
          description: The category of dishes to retrieve
          schema:
            type: string
        - name: sort
          in: query
          required: false
          description: Sorting order for dishes
          schema:
            type: string
            enum: [AZ, ZA, PRICE_ASC, PRICE_DESC, DATE_ASC, DATE_DESC, RATE_ASC, RATE_DESC]
      responses:
        '200':
          description: Information about dishes in the specified category
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    menuId:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                      format: float
                    availability:
                      type: boolean
                    rating:
                      type: number
                      format: float
        '400':
          description: Bad request (invalid parameters)
        '404':
          description: No dishes found for the given category
